---

- hosts: localhost
  gather_facts: no

  vars:
    marker: "{{ lookup('env', 'marker') | default('none', true) | lower | trim }}"
    types: alj
    tear_down: true
    max_send_time: 3600
    pre_sleep: 0
    post_sleep: 0
    mode: "{{ lookup('env', 'marker') | default('debug', true) }}"
    marker_bin: "{{ lookup('env', 'marker_bin') | default('./' ~ mode ~ '/bin', true) }}"
    rust_log: debug

  tasks:
  - name: stop processes
    shell: |
      killall -9 jal-local-store || true
      killall -9 jal_subscribe || true
      killall -9 jaldb_inline_filter || true
      killall -9 jald || true
      #rm -f {{cwd}}/jald_record_socket
      rm -f {{cwd}}/jald_filter_socket*
      rm -f {{cwd}}/*.sock

  - name: clear local store database
    file:
        path: '{{cwd}}/testdb'
        state: absent

  - name: clear subscriber database
    file:
        path: '{{cwd}}/subdb'
        state: absent

  - name: make local store database directory
    file:
        path: '{{cwd}}/testdb'
        state: directory

  - name: make subscriber database directory
    file:
        path: '{{cwd}}/subdb'
        state: directory

  - name: copy DB_CONFIG 1
    copy:
        mode: 0640
        src:  '{{cwd}}/test-input/LMDB_CONFIG'
        dest: '{{cwd}}/subdb'

  - name: copy DB_CONFIG 2
    copy:
        mode: 0640
        src:  '{{cwd}}/test-input/LMDB_CONFIG'
        dest: '{{cwd}}/testdb'

  - name: pre-sleep
    shell: |
      sleep {{ pre_sleep }}

  - name: start local store
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      umask 027
      ./{{mode}}/bin/jal-local-store -c ./test-input/local_store.cfg --no-daemon 2>./ls.err 1>./ls.out &

  - name: start Rust marker ({{marker_bin}}/jaldb_inline_filter)
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      RUST_LOG={{rust_log}} {{marker_bin}}/jaldb_inline_filter -c ./test-input/jaldb-filter.toml -d {{cwd}}/testdb 2>./jald_filter.err 1>./jald_filter.out &
    when: marker == 'rust'

  - name: start subscriber
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      #valgrind --log-file=valgrind-out.txt ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe.cfg -d 2>./subd.err 1>./subd.out &
      ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe.cfg -d 2>./subd.err 1>./subd.out &

#  - name: check subscriber database directory exists
#    stat:
#        path: '{{cwd}}/subdb/lock.mdb'
#    register: subscriber_stat
#
#  - name: Fail if file does not exists
#    fail:
#      msg: 'jal_subscriber did not start correctly'
#    when: subscriber_stat.stat.exists == False

  - name: start jald
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jald -c ./test-input/jald2.cfg --no-daemon -d -f 2>./jald.err 1>./jald.out &

  - name: sleep
    shell: |
      sleep 5

  - name: send logs
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
        #async: "{{ max_send_time }}"
        #poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t l'
    when: '"l" in types'

  - name: send journals
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
        #async: "{{ max_send_time }}"
        #poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t j'
    when: '"j" in types'

  - name: send journal FDs
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
        #async: "{{ max_send_time }}"
        #poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t f'
    when: '"f" in types'

  - name: send audits
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
        #async: "{{ max_send_time }}"
        #poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t a'
    when: '"a" in types'

  - name: sleep
    shell: |
      sleep 5
      PID=`/usr/sbin/pidof ./{{mode}}/bin/jald`
      (( cpu="10" ))
      (( retry_count=0 ))
      while [ $cpu != "0.0" ]
      do
        sleep 1
        cpu=`top -b -n 1 -p $PID | grep -P -m 7 $PID | awk '{print $9}'`
        if [[ $cpu == "0.0" ]] && [[ $retry_count < 5 ]]; then
          (( cpu="10" ))
          (( retry_count=$retry_count + 1 ))
        else
          (( retry_count=0 ))
        fi
      done
      exit 0
    when: tear_down | bool

  - name: post-sleep
    shell: |
      sleep {{ post_sleep }}

  - name: jaldb_tool testdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h testdb
    register: jaldb_tool_testdb_output
    when: tear_down | bool

  - name: jaldb_tool subdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h subdb
    register: jaldb_tool_subdb_output
    when: tear_down | bool

  - name: jaldb_tool output
    shell: |
      cd '{{cwd}}'
      echo '{{ jaldb_tool_testdb_output.stdout }}' > jaldb_tool_output.txt
      echo '{{ jaldb_tool_subdb_output.stdout }}' >> jaldb_tool_output.txt
    when: tear_down | bool

  - name: jaldb_tail
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jaldb_tail -h testdb/ -t j|grep -P -m 1 '\dT\d'|sed 's/_.*//'|sed 's/\s//'
    register: jaldb_tail_output
    when: tear_down | bool

  - name: jal_dump
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      #valgrind --log-file=valgrind-out.txt ./{{mode}}/bin/jal_dump -h testdb/ -u '{{ jaldb_tail_output.stdout }}' -d p -t j
      ./{{mode}}/bin/jal_dump -h testdb/ -u '{{ jaldb_tail_output.stdout }}' -d m -t j
    register: jal_dump_output
    when: tear_down | bool

  - name: jal_dump output
    shell: |
      cd '{{cwd}}'
      echo '{{ jal_dump_output.stdout }}' >> jaldb_tool_output.txt
    when: tear_down | bool

  - name: end processes
    shell: |
      killall jal-local-store || true
      killall jal_subscribe || true
      killall jaldb_inline_filter || true
      killall jald || true
      rm -f {{cwd}}/jald_record_socket_*
      rm -f {{cwd}}/jald_filter_socket
      rm -f {{cwd}}/*.sock
    when: tear_down | bool

  - name: build cov report
    shell: |
      cd '{{cwd}}'
      echo '{{cwd}}' >> jaldb_tool_output.txt
      mkdir cov_integration
      rm -fr cov_integration/*
      lcov -q -t JalopIntegrationTest --directory debug -b '{{cwd}}' --capture --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info /usr/\* --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info '{{cwd}}'/debug/src/\*/test/\* --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info '{{cwd}}'/src/\*/test/\* --output-file cov_integration/app.info
      cd cov_integration
      genhtml --show-details -k app.info
    when: mode == "debug"
