---

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: stop processes
    shell: |
      killall {{cwd}}/{{mode}}/bin/jal-local-store || true
      killall {{cwd}}/{{mode}}/bin/jal_subscribe || true
      killall {{cwd}}/{{mode}}/bin/jald || true

  - name: clear local store database
    file:
        path: '{{cwd}}/testdb'
        state: absent

  - name: clear subscriber database
    file:
        path: '{{cwd}}/subdb'
        state: absent

  - name: remove socket
    file:
        path: '{{cwd}}/jal.sock'
        state: absent

  - name: make local store database directory
    file:
        path: '{{cwd}}/testdb'
        state: directory

  - name: make subscriber database directory
    file:
        path: '{{cwd}}/subdb'
        state: directory

  - name: start local store
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jal-local-store -c ./test-input/local_store.cfg --no-daemon 2</dev/null 1</dev/null &

  - name: start subscriber
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe.cfg 2</dev/null 1</dev/null &

#  - name: check subscriber database directory exists
#    stat:
#        path: '{{cwd}}/subdb/lock.mdb'
#    register: subscriber_stat
#
#  - name: Fail if file does not exists
#    fail:
#      msg: 'jal_subscriber did not start correctly'
#    when: subscriber_stat.stat.exists == False

  - name: start jald
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
      chdir: '{{cwd}}'
      cmd: ./{{mode}}/bin/jald -c ./test-input/jald.cfg

  - name: send logs
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    async: 45
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n 10 -t l'

  - name: send journals
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n 10 -t j'

  - name: send audits
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n 10 -t a'

  - name: sleep 2
    shell: sleep 2

  - name: jaldb_tool testdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h testdb
    register: jaldb_tool_testdb_output

  - name: jaldb_tool subdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h subdb
    register: jaldb_tool_subdb_output

  - name: jaldb_tool output
    shell: |
      cd '{{cwd}}'
      echo '{{ jaldb_tool_testdb_output.stdout }}' > jaldb_tool_output.txt
      echo '{{ jaldb_tool_subdb_output.stdout }}' >> jaldb_tool_output.txt

  - name: jaldb_tail
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jaldb_tail -h testdb/ -t l|grep -P -m 1 '\dT\d'|sed 's/_.*//'|sed 's/\s//'
    register: jaldb_tail_output

  - name: jal_dump
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jal_dump -h testdb/ -u '{{ jaldb_tail_output.stdout }}' -d m -t l
    register: jal_dump_output

  - name: jal_dump output
    shell: |
      cd '{{cwd}}'
      echo '{{ jal_dump_output.stdout }}' >> jaldb_tool_output.txt

  - name: end processes
    shell: |
      killall {{cwd}}/{{mode}}/bin/jal-local-store || true
      killall {{cwd}}/{{mode}}/bin/jald || true
      killall {{cwd}}/{{mode}}/bin/jal_subscribe || true

  - name: build cov report
    shell: |
      cd '{{cwd}}'
      echo '{{cwd}}' >> jaldb_tool_output.txt
      mkdir cov_integration
      rm -fr cov_integration/*
      lcov -q -t JalopIntegrationTest --directory debug -b '{{cwd}}' --capture --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info /usr/\* --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info '{{cwd}}'/debug/src/\*/test/\* --output-file cov_integration/app.info
      lcov -q --remove cov_integration/app.info '{{cwd}}'/src/\*/test/\* --output-file cov_integration/app.info
      cd cov_integration
      genhtml --show-details -k app.info
    when: mode == "debug"
#call with this command from jalop home
##ansible-playbook -i src/test_utils/scripts/ansible/ansible_inventory.ini src/test_utils/scripts/ansible/local-store-pub-sub-tests_debug.yml -e cwd=`pwd` -e mode=debug
