---
# ansible-playbook  src/test_utils/scripts/ansible/multi-subscriber-rust.yml  -e cwd=`pwd` -e rcnt=3 -e mode=release
- hosts: localhost
  gather_facts: no

  vars:
    types: aljf
    mode: release
    rcnt: 6000
    delay: 20
    log_dir: '{{cwd}}/test_logs'
    filter: "yes"
    subd: "c"
    fs: 
    jald: "rust"
    
  tasks:
  - name: stop processes
    shell: |
      killall -9 jal-local-store || true
      killall -9 jal_subscribe || true
      killall -9 jaldb_inline_filter || true
      killall -9 jald || true
      killall -9 jald_rs || true
      killall -9 java || true
      rm -f {{cwd}}/jald_filter_socket*
      rm -f {{cwd}}/*.sock

  - name: clear databases
    shell: |
      cd '{{cwd}}'
      rm -fr testdb
      rm -fr subdb
      rm -fr subdb2
      rm -fr subdb3
      mkdir testdb
      mkdir subdb
      mkdir subdb2
      mkdir subdb3
      cp test-input/LMDB_CONFIG testdb
      cp test-input/LMDB_CONFIG subdb
      cp test-input/LMDB_CONFIG subdb2
      cp test-input/LMDB_CONFIG subdb3
      rm -fr '{{log_dir}}'
      mkdir -p '{{log_dir}}'

  - name: start local store
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      umask 027
      ./{{mode}}/bin/jal-local-store -c ./test-input/local_store.cfg --no-daemon 2>./ls.err 1>./ls.out &

  - name: start Rust filter
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      RUST_LOG=debug ./{{mode}}/bin/jaldb_inline_filter -c ./test-input/jaldb-filter.toml -d ./testdb 2>{{log_dir}}/jald_filter.err 1>{{log_dir}}/jald_filter.out &
    when: filter == "yes"

  - name: start jald_rs w/filter
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      RUST_LOG=warn ./{{mode}}/bin/jald_rs -c ./test-input/jald2subscribers.toml 2>{{log_dir}}/jald_rs.err 1>{{log_dir}}/jald_rs.out &
    when: jald == "rust"

  - name: start subscriber
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe.cfg 2>{{log_dir}}/subd.err 1>{{log_dir}}/subd.out &

  - name: start subscriber 2
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      ./{{mode}}/bin/jal_subscribe -c ./test-input/jal_subscribe_live.cfg 2>{{log_dir}}/subd2.err 1>{{log_dir}}/subd2.out &

  - name: sleep for subscribers
    shell: |
      sleep 10

  - name: send logs
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    async: 3600
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t l'
    when: '"l" in types'

  - name: send journals
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    async: 3600
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t j'
    when: '"j" in types'

  - name: send journal FDs
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    async: 3600
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t f'
    when: '"f" in types'

  - name: send audits
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    async: 3600
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './{{mode}}/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n {{rcnt}} -t a'
    when: '"a" in types'

  - name: sleep
    shell: |
      sleep '{{delay}}'
      PID=`/usr/sbin/pidof ./{{mode}}/bin/jald`
      if [[ '{{jald}}' == 'rust' ]]; then
        PID=`/usr/sbin/pidof ./{{mode}}/bin/jald_rs`
      fi
      (( cpu="10" ))
      (( retry_count=0 ))
      while [ $cpu != "0.0" ]
      do
        sleep 1
        cpu=`top -b -n 1 -p $PID | grep -P -m 7 $PID | awk '{print $9}'`
        if [[ $cpu == "0.0" ]] && [[ $retry_count < 5 ]]; then
          (( cpu="10" ))
          (( retry_count=$retry_count + 1 ))
        else
          (( retry_count=0 ))
        fi
      done
      exit 0

  - name: jaldb_tool testdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h testdb
    register: jaldb_tool_testdb_output

  - name: jaldb_tool subdb
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h subdb
    register: jaldb_tool_subdb_output

  - name: jaldb_tool subdb2
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    command:
        chdir: '{{cwd}}'
        cmd: ./{{mode}}/bin/jaldb_tool -h subdb2
    register: jaldb_tool_subdb2_output

  - name: jaldb_tool output
    environment:
      LD_LIBRARY_PATH: '{{cwd}}/{{mode}}/lib'
    shell: |
      cd '{{cwd}}'
      echo "[" > {{log_dir}}/jaldb_tool_output.txt
      echo '{{ jaldb_tool_testdb_output.stdout }}' >> {{log_dir}}/jaldb_tool_output.txt
      echo "," >> {{log_dir}}/jaldb_tool_output.txt
      echo '{{ jaldb_tool_subdb_output.stdout }}' >> {{log_dir}}/jaldb_tool_output.txt
      echo "," >> {{log_dir}}/jaldb_tool_output.txt
      echo '{{ jaldb_tool_subdb2_output.stdout }}' >> {{log_dir}}/jaldb_tool_output.txt
      echo "]" >> {{log_dir}}/jaldb_tool_output.txt

  - name: end processes
    shell: |
      killall jal-local-store || true
      killall jald || true
      killall jald_rs || true
      sleep 2
      killall jal_subscribe || true
      killall jaldb_inline_filter || true
      killall java || true
      rm -f {{cwd}}/jald_filter_socket*
      rm -f {{cwd}}/*.sock
