import os
import string
Import('*')

tests = []

testEnv = env.Clone()
# The test-dept macros trigger this warning, so disable it for all the test
# drivers.
testEnv.Append(CCFLAGS=' -Wno-format-nonliteral -Wno-unreachable-code -DSCHEMAS_ROOT=\\"' + testEnv['SOURCE_ROOT'] + '/schemas/\\" -DTEST_INPUT_ROOT=\\"' + testEnv['SOURCE_ROOT'] + '/test-input/\\" ')
testEnv.Append(CPPPATH=":#/src/test_utils/src")

errorCallbackObj = env.SharedObject(os.path.join('..','src', 'jal_error_callback.c'))
allocObj = env.SharedObject(os.path.join('..','src', 'jal_alloc.c'))
base64Obj = env.SharedObject(os.path.join('..','src', 'jal_base64.c'))

tests.append(testEnv.TestDeptTest('test_jal_error_callback.c', other_sources=[], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_alloc.c', other_sources=[errorCallbackObj], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_digest.c', other_sources=[errorCallbackObj, allocObj], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_base64.c',
	other_sources=[allocObj, errorCallbackObj])[0].abspath)
common_tests = env.Alias('common_tests', tests, 'test_dept ' + " ".join(tests))
AlwaysBuild(common_tests)
env.Depends(all_tests, common_tests)


