import os
import string
Import('*')

tests = []

testEnv = env.Clone()
# We get these warnings in the tests. Disable for these tests only.
# -Wno-format-nonliteral: Because we're using assert_equals on non-string types. Note that assert_equals_int et. al. are deprecated and will cause a failure/error.
# -fcommon needed to restore original gcc behavior in rhel9 to prevent multiple definition linker errors
ccflags = '-fcommon -Wno-format-nonliteral -DSCHEMAS_ROOT=\\"' + testEnv['SOURCE_ROOT'] + '/schemas/\\" -DTEST_INPUT_ROOT=\\"' + testEnv['SOURCE_ROOT'] + '/test-input/\\" '

testEnv.Append(CPPPATH="#/src/test_utils/src")
testEnv.Append(CCFLAGS=ccflags.split())

errorCallbackObj = env.SharedObject(os.path.join('..','src', 'jal_error_callback.c'))
allocObj = env.SharedObject(os.path.join('..','src', 'jal_alloc.c'))
base64Obj = env.SharedObject(os.path.join('..','src', 'jal_base64.c'))
digestObj = env.SharedObject(os.path.join('..','src', 'jal_digest.c'))

tests.append(testEnv.TestDeptTest('test_jal_error_callback.c', other_sources=[], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_alloc.c', other_sources=[errorCallbackObj], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_digest.c', other_sources=[errorCallbackObj, allocObj], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_base64.c',
	other_sources=[allocObj, errorCallbackObj])[0].abspath)

tests.append(testEnv.TestDeptTest('test_jal_xml_utils.c',
	other_sources=[test_utils, errorCallbackObj, allocObj, base64Obj, digestObj])[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_fs_utils.c',
	other_sources=[allocObj, errorCallbackObj, test_utils], useProxies=True)[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_byteswap.c', other_sources=[])[0].abspath)
tests.append(testEnv.TestDeptTest('test_jal_config.c', other_sources=[], useProxies=True)[0].abspath)

common_tests = env.Alias('common_tests', tests, 'test_dept ' + " ".join(tests))
AlwaysBuild(common_tests)
env.Depends(all_tests, common_tests)
