Import('*')
import os
import shutil
import subprocess
from Utils import rhel_version
from Utils import install_for_build

env = env.Clone()
os.system("pwd")
rhel_ver = rhel_version()
variant = env['variant']
cargo_flags = f"rhel{rhel_ver}"

try:
	if not 'install' in BUILD_TARGETS and not 'doc' in BUILD_TARGETS and not 'cov' in BUILD_TARGETS:
		if env.GetOption('clean'):
			print("CARGO Cleaning")
			subprocess.run(["cargo", "clean"], check=True, shell=False)
			Return("")
		if (env['variant'] == 'release'):

			#Checks if scons test
			if 'tests' in BUILD_TARGETS:
				print("CARGO Test Release")
				subprocess.run(["cargo", "test", "--release", "--features", cargo_flags], check=True, shell=False)
			else:
				print("CARGO Build Release")
				subprocess.run(["cargo", "build", "--release", "--features", cargo_flags], check=True, shell=False)
				print("CARGO Installing Release")
				subprocess.run(["mkdir", "-p", "../../release/bin"], check=True, shell=False)
				subprocess.run(["cp", "-f", "./target/release/jaldb_inline_filter", "../../release/bin"], check=True, shell=False)
				subprocess.run(["cp", "-f", "./target/release/jald_rs", "../../release/bin"], check=True, shell=False)
			Return("")
		if (env['variant'] == 'debug'):
			#Checks if scons test
			if 'tests' in BUILD_TARGETS:
				print("CARGO Test Debug")
				subprocess.run(["cargo", "test", "--features", cargo_flags], check=True, shell=False)
			else:
				print("CARGO Build Debug")
				subprocess.run(["cargo", "build", "--features", cargo_flags], check=True, shell=False)
				print("CARGO Installing Debug")
				subprocess.run(["mkdir", "-p", "../../debug/bin"], check=True, shell=False)
				subprocess.run(["cp", "-f", "./target/debug/jaldb_inline_filter", "../../debug/bin"], check=True, shell=False)
				subprocess.run(["cp", "-f", "./target/debug/jald_rs", "../../debug/bin"], check=True, shell=False)
			Return("")
except subprocess.CalledProcessError as e:
	print(e)
	print("ERROR: JALoP Rust build failed.")
	os._exit(2)

print("CARGO Doing Nothing")
Return("")
