Import('*')
from Utils import add_project_lib
from Utils import install_for_build
from Utils import rhel_version
import os
import shutil
env = env.Clone()

rhel_ver = rhel_version()
cargo_flags = f"--features rhel{rhel_ver}"

env['ENV']['JALOP_ROOT'] = Dir('#').abspath

#Copies latest source
if not env.GetOption('clean'):
	destPath =  Dir('.').abspath + "/"
	os.system("cp -rTf " + Dir('.').srcnode().abspath + "/ " + destPath + "/")
	#Removes bindings.rs to ensure regeneration during build
	os.system("sh " + Dir('.').srcnode().abspath + "/remove_bindings.sh " +  destPath)

if (env['variant'] == 'release'):
	cargo = Builder(action=f"cargo clean && cargo build --release {cargo_flags}", chdir=1)
else:
	cargo = Builder(action=f"cargo clean && cargo build {cargo_flags}", chdir=1)

env.Append(BUILDERS = {'Cargo' : cargo})
jalop_rust = env.Cargo("Cargo.toml")
env.AlwaysBuild(jalop_rust)

if (env['variant'] == 'release'):
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, "target/release/jaldb_inline_filter"))

rust_tests = env.Alias(target="tests", source=None,
		action=[f"export RUSTFLAGS='-L ../../lib'; cd debug/src/jalop-rust; cargo test {cargo_flags}"])
env.AlwaysBuild(rust_tests)

Return("jalop_rust")
