Import('*')
from Utils import install_for_build
from Utils import add_project_lib

if env['variant'] == 'release':
	incdir = env['DESTDIR'] + env.subst(env['INCLUDEDIR'])
	env.Alias('install', env.Install(incdir + '/jalop/', "jaldb_context.h"))
	env.Alias('install', env.Install(incdir + '/jalop/', "jaldb_context.hpp"))

env = env.Clone()

sources = env.Glob("*.c") + env.Glob("*.cpp")

add_project_lib(env, 'lib_common', 'jal-common')

db_lib = env.SharedLibrary(target='jal-db', source=[sources])
env.Default(db_lib)

install_for_build(env, 'lib', db_lib)
if (env['variant'] == 'release'):
	libdir = env['DESTDIR'] + env.subst(env['LIBDIR'])
	env.Alias('install', env.Install(libdir, db_lib))

Return("db_lib env")
