import os

from Utils import install_for_build
from Utils import add_project_lib

Import('*')

env = env.Clone();
sources = env.Glob("*.c")

ccflags = '-DSCHEMAS_ROOT=\\"' + env['SOURCE_ROOT']  + '/schemas/\\"'

env.Append(CCFLAGS=ccflags.split())

env.MergeFlags({'CPPPATH':'#src/producer_lib/include:#src/lib_common/include:.'.split(':')})

add_project_lib(env, 'producer_lib', 'jal-producer')
add_project_lib(env, 'lib_common', 'jal-common')


jalp_test = env.Program(target='jalp_test', source=sources)
env.Depends(jalp_test, [lib_common, producer_lib])
env.Default(jalp_test)

install_for_build(env, 'bin', jalp_test)
Return("jalp_test")
