import os
import string
Import('*')

tests = []

env = env.Clone()

# The test code trigger warnings we'd just assume ignore.
ccflags = ' -Wno-format-nonliteral -Wno-unreachable-code '
env.Append(CCFLAGS=ccflags.split())

tests.append(env.TestDeptTest('test_jaln_publisher_callbacks.c',
	other_sources=[lib_common])[0].abspath)
tests.append(env.TestDeptTest('test_jaln_connection_callbacks.c',
	other_sources=[lib_common])[0].abspath)

net_lib_tests = env.Alias('net_lib_tests', tests, 'test_dept ' + " ".join(tests))
AlwaysBuild(net_lib_tests)
env.Depends(all_tests, net_lib_tests)

