Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = env.Clone()
add_project_lib(env, 'db_layer', 'jal-db')
env.MergeFlags(env['bdb_cflags'])
env.MergeFlags(env['bdb_ldflags'])

sources = env.Glob("*.cpp")

env.MergeFlags({'CPPPATH':'#src/db_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})
env.MergeFlags("-Wno-shadow")

jal_dump_objs = env.SharedObject(source=sources)

jal_dump = env.Program(target='jal_dump', source=jal_dump_objs)
env.Default(jal_dump)
if env['variant'] == 'release':
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, jal_dump))

install_for_build(env, 'bin', jal_dump)

Return("jal_dump")
