[db]
path = "testdb"
poll_time = 1

[control-socket]
path = "jald_filter_socket_request"
buffer = 4096

[record-socket]
path = "jald_filter_socket"
timeout = 30
buffer = 256

[seccomp]
enabled = false
debug = false

initial = ["access", "arch_prctl", "bind", "epoll_create1", "eventfd2", "execve", "getrandom", "ioctl", "listen", "poll", "prlimit64", "seccomp", "set_tid_address", "socketpair"]
final = ["accept4", "connect", "exit", "getpid", "madvise", "pwrite64", "recvfrom", "rt_sigreturn", "sendmsg", "writev"]
both = ["brk", "clone3", "close", "epoll_ctl", "epoll_wait", "exit_group", "fcntl", "fstat", "fstatfs", "futex", "lseek", "mmap", "mprotect", "munmap", "newfstatat", "openat", "prctl", "pread64", "read", "rseq", "rt_sigaction", "rt_sigprocmask", "sched_getaffinity", "sched_yield", "set_robust_list", "sigaltstack", "socket", "statx", "stat", "write"]
