#!/bin/bash
RPMDIR=rpmbuild
PKG_NAME=jalop
TAR_CONTENTS="../release/bin/ ../release/lib ../test-input ../schemas"

function makerpm() {
    TOPDIR=$(pwd)/$RPMDIR

    rm -fr $RPMDIR
    mkdir -p $RPMDIR/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

    tar -cf $PKG_NAME.tar $TAR_CONTENTS

    cp $PKG_NAME.spec $RPMDIR/SPECS/
    cp $PKG_NAME.tar  $RPMDIR/SOURCES/

    if [[ "$PATCH_VERSION" != "" ]]; then
        spec_file="$RPMDIR/SPECS/$PKG_NAME.spec"
        spec_version=$(grep "Version: " $spec_file | tr -s ' ' | cut -d' ' -f2)
        patched_version="${spec_version}~${PATCH_VERSION}"
        sed -i "s#Version:\s*${spec_version}#Version: ${patched_version}#" $spec_file
    fi

    cd "$TOPDIR" && rpmbuild --define "_topdir $TOPDIR" -bb SPECS/$PKG_NAME.spec
    cd ../ || exit
    cp $RPMDIR/RPMS/x86_64/*.rpm ./
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    makerpm
fi
