Import('*')
from Utils import install_for_build
from Utils import add_project_lib

testserver = env.Alias('testserver')

testserver_env = env.Clone()

testserver_env.MergeFlags({'CPPPATH':'#src/lib_common/include:.'.split(':')})

server = testserver_env.Program(target='dummy_local_store', source=["server.c"])
add_project_lib(testserver_env, 'lib_common', 'jal-common')
testserver_env.Depends(server, lib_common)

testserver_env.Depends(testserver, server)
install_for_build(testserver_env, 'bin', server)

env.Default(testserver)
