Import('*')

testserver = utilsEnv.Alias('testserver')

testserver_env = utilsEnv.Clone()

server = testserver_env.Program(target='dummy_local_store', source=["server.c", lib_common])

testserver_env.Depends(testserver, server)

utilsEnv.Default(testserver)
