Import('*')
from Utils import install_for_build
from Utils import add_project_lib

testserver = utilsEnv.Alias('testserver')

testserver_env = utilsEnv.Clone()

server = testserver_env.Program(target='dummy_local_store', source=["server.c"])
add_project_lib(testserver_env, 'lib_common', 'jal-common')
testserver_env.Depends(server, lib_common)

testserver_env.Depends(testserver, server)
install_for_build(testserver_env, 'bin', server)

utilsEnv.Default(testserver)
