import ConfigDotH

Import('*')

sources = []
for source in (env.Glob("*.c") + env.Glob("*.cpp")):
	sources.append(source)

# build config.h
configh = env.Command('jalp_config_internal.h',
		'jalp_config_internal.h.in', ConfigDotH.config_h_build)

producer_lib = env.SharedLibrary(target='jal-producer', source=sources)
env.Default(producer_lib)
if (env['release']):
	libdir = env['DESTDIR'] + env.subst(env['LIBDIR'])
	env.Install(libdir, producer_lib)
	env.Alias('install', libdir)

Return("producer_lib")
