Import('*')

sources = []
for source in (env.Glob("*.c") + env.Glob("*.cpp")):
	sources.append(source)

producer_lib = env.SharedLibrary(target='jal-producer', source=sources)
env.Default(producer_lib)
Return("producer_lib")
