/* automatically generated by rust-bindgen 0.69.5 */

pub type uuid_t = [::std::os::raw::c_uchar; 16usize];
pub const jaldb_status_JALDB_E_INVAL: jaldb_status = -1024;
pub const jaldb_status_JALDB_E_UNKNOWN: jaldb_status = -1023;
pub const jaldb_status_JALDB_E_DB: jaldb_status = -1022;
pub const jaldb_status_JALDB_E_ALREADY_CONFED: jaldb_status = -1021;
pub const jaldb_status_JALDB_E_NO_MEM: jaldb_status = -1020;
pub const jaldb_status_JALDB_E_UNINITIALIZED: jaldb_status = -1019;
pub const jaldb_status_JALDB_E_INTERNAL_ERROR: jaldb_status = -1018;
pub const jaldb_status_JALDB_E_INITIALIZED: jaldb_status = -1017;
pub const jaldb_status_JALDB_E_CORRUPTED: jaldb_status = -1016;
pub const jaldb_status_JALDB_E_NONCE: jaldb_status = -1015;
pub const jaldb_status_JALDB_E_NOT_FOUND: jaldb_status = -1014;
pub const jaldb_status_JALDB_E_READ_ONLY: jaldb_status = -1013;
pub const jaldb_status_JALDB_E_QUERY_EVAL: jaldb_status = -1012;
pub const jaldb_status_JALDB_E_NOT_IMPL: jaldb_status = -1011;
pub const jaldb_status_JALDB_E_SIZE: jaldb_status = -1010;
pub const jaldb_status_JALDB_E_REJECT: jaldb_status = -1009;
pub const jaldb_status_JALDB_E_LAYOUT_VERSION_UNKNOWN: jaldb_status = -1008;
pub const jaldb_status_JALDB_E_NETWORK_DISCONNECTED: jaldb_status = -1007;
pub const jaldb_status_JALDB_E_INVAL_TIMESTAMP: jaldb_status = -1006;
pub const jaldb_status_JALDB_E_INVAL_RECORD_TYPE: jaldb_status = -1005;
pub const jaldb_status_JALDB_OK: jaldb_status = 0;
#[doc = " Enumeration for error codes returned by DB layer calls."]
pub type jaldb_status = ::std::os::raw::c_int;
#[doc = "!< Indicates a Journal Record */"]
pub const jaldb_rec_type_JALDB_RTYPE_JOURNAL: jaldb_rec_type = 1;
#[doc = "!< Indicates an Audit Record */"]
pub const jaldb_rec_type_JALDB_RTYPE_AUDIT: jaldb_rec_type = 2;
#[doc = "!< Indicates a Log Record */"]
pub const jaldb_rec_type_JALDB_RTYPE_LOG: jaldb_rec_type = 4;
#[doc = "!< Indicates the record type is unknown/unset */"]
pub const jaldb_rec_type_JALDB_RTYPE_UNKNOWN: jaldb_rec_type = 8;
#[doc = " Enum used to distinguish between record types"]
pub type jaldb_rec_type = ::std::os::raw::c_uint;
pub const jaldb_sync_stat_JALDB_NOT_CONFIRMED: jaldb_sync_stat = 0;
pub const jaldb_sync_stat_JALDB_NOT_SENT: jaldb_sync_stat = 1;
pub const jaldb_sync_stat_JALDB_SENT: jaldb_sync_stat = 2;
pub const jaldb_sync_stat_JALDB_SYNCED: jaldb_sync_stat = 3;
pub type jaldb_sync_stat = ::std::os::raw::c_uint;
#[doc = " This structure is used to insert/retrieve records from the database."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jaldb_record {
    #[doc = "!< The nonce used for network communications about this record."]
    pub network_nonce: *mut ::std::os::raw::c_char,
    #[doc = "!< The process ID of the process that created the record."]
    pub pid: u64,
    #[doc = "!< The User ID of process that generated the event."]
    pub uid: u64,
    #[doc = "!< Structure containing data regarding the system metadata, or NULL."]
    pub sys_meta: *mut jaldb_segment,
    #[doc = "!< Structure containing data regarding the app metadata, or NULL."]
    pub app_meta: *mut jaldb_segment,
    #[doc = "!< Structure containing data regarding the payload (journal audit or log data), or NULL."]
    pub payload: *mut jaldb_segment,
    #[doc = "!< The source of this record."]
    pub source: *mut ::std::os::raw::c_char,
    #[doc = "!< The hostname of the machine that created the record."]
    pub hostname: *mut ::std::os::raw::c_char,
    #[doc = "!< The timestamp of this record in XML Schema DateTime format."]
    pub timestamp: *mut ::std::os::raw::c_char,
    #[doc = "!< The username of the process that generated the event."]
    pub username: *mut ::std::os::raw::c_char,
    #[doc = "!< The security label of the process that generated the event."]
    pub sec_lbl: *mut ::std::os::raw::c_char,
    #[doc = "!< The in-database version of the record, currently always \\p 1."]
    pub version: ::std::os::raw::c_int,
    #[doc = "!< The type of the record"]
    pub type_: jaldb_rec_type,
    #[doc = "!< Indicates the outbound record status."]
    pub synced: jaldb_sync_stat,
    #[doc = "!< Indicates whether the inbound record has been confirmed as valid via digest_response from the publisher."]
    pub confirmed: ::std::os::raw::c_char,
    #[doc = "!< Indicates if the uid filed is valid."]
    pub have_uid: ::std::os::raw::c_char,
    #[doc = "!< The UUID of the machine that created the record."]
    pub host_uuid: uuid_t,
    #[doc = "!< The UUID of the record."]
    pub uuid: uuid_t,
}
#[test]
fn bindgen_test_layout_jaldb_record() {
    const UNINIT: ::std::mem::MaybeUninit<jaldb_record> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<jaldb_record>(),
        136usize,
        concat!("Size of: ", stringify!(jaldb_record))
    );
    assert_eq!(
        ::std::mem::align_of::<jaldb_record>(),
        8usize,
        concat!("Alignment of ", stringify!(jaldb_record))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).network_nonce) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(network_nonce)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pid) as usize - ptr as usize },
        8usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(pid))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uid) as usize - ptr as usize },
        16usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(uid))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sys_meta) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(sys_meta)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).app_meta) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(app_meta)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).payload) as usize - ptr as usize },
        40usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(payload))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).source) as usize - ptr as usize },
        48usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(source))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).hostname) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(hostname)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).timestamp) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(timestamp)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).username) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(username)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sec_lbl) as usize - ptr as usize },
        80usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(sec_lbl))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).version) as usize - ptr as usize },
        88usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(version))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        92usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(type_))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).synced) as usize - ptr as usize },
        96usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(synced))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).confirmed) as usize - ptr as usize },
        100usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(confirmed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).have_uid) as usize - ptr as usize },
        101usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(have_uid)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).host_uuid) as usize - ptr as usize },
        102usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_record),
            "::",
            stringify!(host_uuid)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uuid) as usize - ptr as usize },
        118usize,
        concat!("Offset of field: ", stringify!(jaldb_record), "::", stringify!(uuid))
    );
}
extern "C" {
    #[doc = " Function to destroy a jaldb_record.\n This will call appropriate destroy functions & free on all of it's members.\n @param [in,out] pprecord The jaldb_record to destroy. This will be set to NULL."]
    pub fn jaldb_destroy_record(pprecord: *mut *mut jaldb_record);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jaldb_context_t {
    _unused: [u8; 0],
}
#[doc = " jaldb_context type"]
pub type jaldb_context = jaldb_context_t;
#[doc = " Sets no LMDB performance flags, this is the slowest, but most reliable setting to prevent data loss or db corruption"]
pub const jaldb_flags_JDB_NONE: jaldb_flags = 0;
#[doc = " Sets no LMDB performance flags, this is the slowest, but most reliable setting to prevent data loss or db corruption"]
pub const jaldb_flags_JDB_READONLY: jaldb_flags = 1;
#[doc = " Sets MDB_NOMETASYNC\n No risk of db corruption, but could lose last transaction"]
pub const jaldb_flags_JDB_LMDB_PERFORMANCE_LEVEL1: jaldb_flags = 2;
#[doc = " Sets MDB_NOMETASYNC | MDB_NOSYNC\n This is the recommended setting and is much faster than JDB_LMDB_PERFORMANCE_LEVEL1.\n No risk of db corruption if file system preserves write order otherwise db corruption is possible.  Also could lose last transaction."]
pub const jaldb_flags_JDB_LMDB_PERFORMANCE_LEVEL2: jaldb_flags = 3;
#[doc = " Sets MDB_NOMETASYNC | MDB_NOSYNC | MDB_WRITEMAP | MDB_MAPASYNC\n WARNING!!! This setting is faster than JDB_LMDB_PERFORMANCE_LEVEL2\n However there is a very high risk of db corruption and data loss in case of a crash or power outage.  Also if this setting is used, all other JAL processes\n must use this exact same setting.  Overall this setting is not recommended to be used if the risk of db corruption is not acceptable."]
pub const jaldb_flags_JDB_LMDB_PERFORMANCE_LEVEL3: jaldb_flags = 4;
#[doc = " Define enum to represent settings for LMDB"]
pub type jaldb_flags = ::std::os::raw::c_uint;
extern "C" {
    #[doc = " Creates an empty DB context.\n\n @return The created empty DB context.\n"]
    pub fn jaldb_context_create() -> *mut jaldb_context;
}
extern "C" {
    #[doc = " Initializes a DB context.\n @param[in] ctx The context to initialize.\n @param[in] db_root The root path of the DB Layer's files. If db_root is\n NULL, then the default is /var/lib/jalop/db.\n @param[in] jdb_flags Bit-packed options to be passed to the db. Specify zero\n or more options using a bitwise or \"|\" with the values specified in the\n jaldb_flags enum.\n @param[in] map_size The lmdb map size in gigabytes (GB)\n @return JAL_OK if the function succeeds or a JAL error code if the function\n fails."]
    pub fn jaldb_context_init(
        ctx: *mut jaldb_context,
        db_root: *const ::std::os::raw::c_char,
        jdb_flags: jaldb_flags,
        map_size: ::std::os::raw::c_int,
    ) -> jaldb_status;
}
extern "C" {
    #[doc = " Destroys a DB context.\n Release all resources associated with this context.\n\n @param[in,out] ctx The context to destroy. *ctx will be set to NULL."]
    pub fn jaldb_context_destroy(ctx: *mut *mut jaldb_context);
}
extern "C" {
    #[doc = " Retrieves a record by nonce.\n\n @param[in] ctx The context.\n @param[in] type The type of record (journal, audit, log).\n @param[in] nonce The nonce of the record being retrieved.\n @param[out] rec This will be filled in as a jaldb_record object if the\n record is found. Note that any segments located on disk will not be opened\n automatically.\n\n @return JAL_OK if the function succeeds or a JAL error code if the function\n fails."]
    pub fn jaldb_get_record(
        ctx: *mut jaldb_context,
        type_: jaldb_rec_type,
        nonce: *const ::std::os::raw::c_char,
        rec: *mut *mut jaldb_record,
    ) -> jaldb_status;
}
extern "C" {
    #[doc = " Finds a given record and marks the sent to 0 or 1 for the remote archive source.\n Note: Is up to the caller to verify valid states for Confirmed and/or Synced before\n   calling this function to update the Sent state.\n\n @param[in] ctx The context.\n @param[in] type The type of record (journal, audit, or log).\n @param[in] nonce The nonce of the record to mark.\n @param[in] target_state The requested state for the Sent flag.\n\n @return JALDB_OK on success, or a different JALDB error code on failure."]
    pub fn jaldb_mark_sent(
        ctx: *mut jaldb_context,
        type_: jaldb_rec_type,
        nonce: *const ::std::os::raw::c_char,
        target_state: ::std::os::raw::c_int,
    ) -> jaldb_status;
}
extern "C" {
    #[doc = " Finds a given record and marks it as synced with a remote source.\n\n @param[in] ctx The context.\n @param[in] type The type of record (journal, audit, or log).\n @param[in] nonce The nonce of the record to mark.\n\n @return JALDB_OK on success, or a different JALDB error code on failure."]
    pub fn jaldb_mark_synced(
        ctx: *mut jaldb_context,
        type_: jaldb_rec_type,
        nonce: *const ::std::os::raw::c_char,
    ) -> jaldb_status;
}
extern "C" {
    #[doc = " Marks all records in a db that are unsynced as unsent.\n\n @param[in] ctx The context.\n @param[in] type The type of record to mark as unsent.\n\n @return JALDB_OK if the function succeeds or an error code."]
    pub fn jaldb_mark_unsynced_records_unsent(ctx: *mut jaldb_context, type_: jaldb_rec_type) -> jaldb_status;
}
extern "C" {
    #[doc = " Retrieves the next chronological record from the database.\n\n @param[in] ctx The context.\n @param[in] type The type of record to retrieve.\n @param[out] nonce The nonce for the returned record.\n @param[out] rec The record from the DB.\n @param[in,out] timestamp The timestamp of the last sent record.\n \t\tOverwritten to the new timestamp when a record is returned\n \t\tCalling with a timestamp less than a previous timestamp\n \t\tmay result in records being sent multiple times.\n\n @return JALDB_OK if the function succeeds or an error code."]
    pub fn jaldb_next_chronological_record(
        ctx: *mut jaldb_context,
        type_: jaldb_rec_type,
        nonce: *mut *mut ::std::os::raw::c_char,
        rec: *mut *mut jaldb_record,
        timestamp: *mut *mut ::std::os::raw::c_char,
    ) -> jaldb_status;
}
extern "C" {
    #[doc = " Retrieves the next un-synced record from the database.\n\n @param[in] ctx The context.\n @param[in] type The type of record to retrieve.\n @param[out] network_nonce The nonce for the returned record.\n @param[out] rec_out The record from the DB.\n\n @return JALDB_OK if the function succeeds or an error code."]
    pub fn jaldb_next_unsynced_record(
        ctx: *mut jaldb_context,
        type_: jaldb_rec_type,
        network_nonce: *mut *mut ::std::os::raw::c_char,
        rec_out: *mut *mut jaldb_record,
    ) -> jaldb_status;
}
pub const jaldb_mark_MARK_UNSYNCED_RECORDS_UNSENT: jaldb_mark = 1;
pub const jaldb_mark_MARK_SENT: jaldb_mark = 2;
pub const jaldb_mark_MARK_SYNCED: jaldb_mark = 3;
pub const jaldb_mark_MARK_UNSENT: jaldb_mark = 4;
pub const jaldb_mark_MARK_ERROR: jaldb_mark = -1;
pub const jaldb_mark_MARK_SUCCESS: jaldb_mark = 0;
pub type jaldb_mark = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mark_request {
    pub mark: jaldb_mark,
    pub record_type: jaldb_rec_type,
    pub nonce: [::std::os::raw::c_char; 128usize],
    pub response: jaldb_mark,
}
#[test]
fn bindgen_test_layout_mark_request() {
    const UNINIT: ::std::mem::MaybeUninit<mark_request> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<mark_request>(),
        140usize,
        concat!("Size of: ", stringify!(mark_request))
    );
    assert_eq!(
        ::std::mem::align_of::<mark_request>(),
        4usize,
        concat!("Alignment of ", stringify!(mark_request))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mark) as usize - ptr as usize },
        0usize,
        concat!("Offset of field: ", stringify!(mark_request), "::", stringify!(mark))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).record_type) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(mark_request),
            "::",
            stringify!(record_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).nonce) as usize - ptr as usize },
        8usize,
        concat!("Offset of field: ", stringify!(mark_request), "::", stringify!(nonce))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).response) as usize - ptr as usize },
        136usize,
        concat!(
            "Offset of field: ",
            stringify!(mark_request),
            "::",
            stringify!(response)
        )
    );
}
#[doc = " Structure representing one component of a JALoP record.\n In the database, the record data may be stored in a separate file on disk,\n or directly in the database. If this segment is stored in a separate\n file, then \\p on_disk is set to \\p 1 (otherwise it is \\p 0). If the record\n is on disk, then \\p fd may be a valid file descriptor. If \\p on_disk is\n \\p 1, then payload is set to the relative path on disk.\n If this segment is stored directly in the database, then \\p on_disk is\n set to 0, \\p fd is set to \\p -1, and \\p payload is the\n contents of the segment.\n \\p length is always the size of segment, regardless of whether it is on\n disk or in the database."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jaldb_segment {
    #[doc = "!< The size of this hunk of data."]
    pub length: u64,
    #[doc = "!< The actual data, or the relative path on disk."]
    pub payload: *mut u8,
    #[doc = "!< The file descriptor for the data."]
    pub fd: ::std::os::raw::c_int,
    #[doc = "!< indicates if the payload is the raw content, or if the data exists on disk."]
    pub on_disk: ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_jaldb_segment() {
    const UNINIT: ::std::mem::MaybeUninit<jaldb_segment> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<jaldb_segment>(),
        24usize,
        concat!("Size of: ", stringify!(jaldb_segment))
    );
    assert_eq!(
        ::std::mem::align_of::<jaldb_segment>(),
        8usize,
        concat!("Alignment of ", stringify!(jaldb_segment))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).length) as usize - ptr as usize },
        0usize,
        concat!("Offset of field: ", stringify!(jaldb_segment), "::", stringify!(length))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).payload) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_segment),
            "::",
            stringify!(payload)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize },
        16usize,
        concat!("Offset of field: ", stringify!(jaldb_segment), "::", stringify!(fd))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).on_disk) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_segment),
            "::",
            stringify!(on_disk)
        )
    );
}
extern "C" {
    #[doc = " Create a timestamp for the Current time in the XML DateTime format which includes\n microseconds.\n\n @return a newly allocated string that contains the current time as an XML\n DateTime string."]
    pub fn jal_gen_timestamp_usec() -> *mut ::std::os::raw::c_char;
}
pub const jaldb_config_status_JALDB_CONFIG_E_LOAD: jaldb_config_status = 1;
pub const jaldb_config_status_JALDB_CONFIG_E_NOTFOUND: jaldb_config_status = 2;
pub const jaldb_config_status_JALDB_CONFIG_E_MEM: jaldb_config_status = 3;
pub const jaldb_config_status_JALDB_CONFIG_OK: jaldb_config_status = 0;
#[doc = " Enumeration for error codes returned by the get_jaldb_config method."]
pub type jaldb_config_status = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct jaldb_config_t {
    pub map_size: ::std::os::raw::c_int,
    pub database_option: *mut ::std::os::raw::c_char,
    pub jdb_flags: jaldb_flags,
}
#[test]
fn bindgen_test_layout_jaldb_config_t() {
    const UNINIT: ::std::mem::MaybeUninit<jaldb_config_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<jaldb_config_t>(),
        24usize,
        concat!("Size of: ", stringify!(jaldb_config_t))
    );
    assert_eq!(
        ::std::mem::align_of::<jaldb_config_t>(),
        8usize,
        concat!("Alignment of ", stringify!(jaldb_config_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).map_size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_config_t),
            "::",
            stringify!(map_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).database_option) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_config_t),
            "::",
            stringify!(database_option)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).jdb_flags) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(jaldb_config_t),
            "::",
            stringify!(jdb_flags)
        )
    );
}
pub type jaldb_config = jaldb_config_t;
extern "C" {
    #[doc = " Parses the LMDB_CONFIG if present and returns the populated jaldb_config_t struct\n\n @param[in] db_root The path to the db root\n @param[out] jdb_config The pointer to the struct containing the parsed LMDB_CONFIG data.\n                          This struct is allocated in this method and must be freed when done.\n\n @return JALDB_CONFIG_OK if the function succeeds or a jaldb_config_status error code if the function\n fails."]
    pub fn get_jaldb_config(
        db_root: *const ::std::os::raw::c_char,
        jdb_config: *mut *mut jaldb_config,
    ) -> jaldb_config_status;
}
extern "C" {
    #[doc = " Frees the jaldb_config pointer returned from the get_jaldb_config method.  This is needed\n for the rust inline filter to free this pointer.\n\n @param[in] jdb_config The jaldb_config pointer to free\n"]
    pub fn free_jaldb_config(jdb_config: *mut *mut jaldb_config);
}
