[package]
name = "jalop"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jaldb_inline_filter"
path = "src/main.rs"

[dependencies.jalop-sys]
path = "sys"

[dependencies.jalop-actors]
path = "actors"

[dependencies]
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
nom = "7"
log = "0.4"
env_logger = "0.11"
libc = "0.2"
nix = { version = "0.29", features = ["uio", "socket"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "sink"] }
async-trait = "0.1"
chrono = "0.4"

[dev-dependencies]
assert_matches = "1.5"

[features]
default = []
rhel9 = ["jalop-sys/rhel9"]
rhel8 = ["jalop-sys/rhel8"]
rhel7 = ["jalop-sys/rhel7"]
