Import('*')
from Utils import add_project_lib

env = env.Clone()

env.MergeFlags({'CPPPATH':('#src/jal_utils/src:#src/db_layer/src:#src/lib_common/include:' +
	'#src/lib_common/src:#src/network_lib/include').split(':')})

env.MergeFlags(env['lfs_cflags'])
env.MergeFlags(env['libconfig_cflags'])
env.MergeFlags(env['libconfig_ldflags'])
env.MergeFlags(env['openssl_cflags'])
env.MergeFlags(env['openssl_ldflags'])
env.MergeFlags(env['vortex_cflags'])
env.MergeFlags(env['vortex_ldflags'])
env.MergeFlags(env['xerces_cflags'])
env.MergeFlags(env['xerces_ldflags'])
env.MergeFlags(env['libuuid_ldflags'])
env.MergeFlags("-Wno-shadow")
env.MergeFlags({'LINKFLAGS':env['dbxml_ldflags']})

add_project_lib(env, 'lib_common', 'jal-common')
add_project_lib(env, 'db_layer', 'jal-db')
add_project_lib(env, 'jal_utils', 'jal-utils')
add_project_lib(env, 'network_lib', 'jal-network')

SConscript('test/SConscript', exports='env all_tests lib_common db_layer jal_utils network_lib test_utils')
network_stores = env.SConscript('src/SConscript', exports='env jal_utils lib_common db_layer network_lib')

Return("network_stores")
