Import('*')
from Utils import add_project_lib

env = env.Clone()

env.MergeFlags({'CPPPATH':('#src/jal_utils/src:#src/db_layer/src:#src/lib_common/include:' +
	'#src/lib_common/src:#src/network_lib/include').split(':')})

env.MergeFlags(env['lfs_cflags'])
env.MergeFlags(env['libconfig_cflags'])
env.MergeFlags(env['libconfig_ldflags'])
env.MergeFlags(env['openssl_cflags'])
env.MergeFlags(env['openssl_ldflags'])
env.MergeFlags(env['axl_cflags'])
env.MergeFlags(env['axl_ldflags'])
env.MergeFlags('-pthread')
env.MergeFlags(env['libxml2_cflags'])
env.MergeFlags(env['libxml2_ldflags'])
env.MergeFlags(env['xmlsec1_cflags'])
env.MergeFlags(env['xmlsec1_ldflags'])
env.MergeFlags(env['libuuid_ldflags'])
env.MergeFlags(env['bdb_cflags'])
env.MergeFlags(env['bdb_ldflags'])
env.MergeFlags("-Wno-shadow")

jald, net_stores_env = env.SConscript('src/SConscript', exports='env jal_utils lib_common db_layer network_lib')

Return("jald")
