.TH JAL_TAIL 8
.SH NAME
.B jal_tail
\-
.SM JALoP
database tail utility
.SH SYNOPSIS
.B jal_tail
[\fIOPTION\fR...]
.SH "DESCRIPTION"
The
.B jal_tail
tool is similar to the UNIX
.BR tail (1)
utility.
The
.B jal_tail
tool queries the specified JAL database and lists the last 20 records by default.
The
.B jal_tail
utility accepts a number of parameters,
including switches to filter the records.
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-follow\fR
Output additional records as the database grows
.TP
\fB\-n\fR, \fB\-\-records=K\fR
Output the most recent \fBK\fR records.
.B jal_tail
uses the serial ID of the JAL record that the JALoP Local Store or JALoP Network Store assigns to determine the most recent records.
.TP
\fB\-\-version\fR
Output the version information and exit.
.TP
\fB\-t\fR, \fB\-\-type=T\fR
Show only records of a particular type.
\fBT\fR may be the letter \fIj\fR (for journal records),
\fIa\fR (for audit records),
or \fIl\fR (for log records).
The default behavior displays log records.
.TP
\fB\-h\fR, \fB\-\-home=H\fR
Specify the root of the JALoP database, defaults to
.I /var/lib/jalop/db/
.TP
\fB\-\-version\fR
Output the version information and exit.
.SH "SEE ALSO"
.BR jald (8),
.BR jal-local-store (8),
.BR jal-local-store.config (5),
.BR jal_dump (8),
.BR jal_purge (8)
.BR jal_query (8),
.BR jal_subscribe (8),

