.TH JAL_SUBSCRIBE.CONFIG 5
.SH NAME
.BR jal_subscribe.config
- configuration file for
.BR jal_subscribe (8)
.SH "DESCRIPTION"
This file is read by
.BR jal_subscribe (8)
and specifies the configuration parameters
such as the host and port to connect to,
and the location of the
.SM JALoP
database of records.
This file follows the format of the libconfig library, where each
configuration setting is in the form "key = value;".
Blank lines and lines starting with "#" are ignored.
String values must be enclosed in double quotes.
All numeric values must have the suffix 'L',
as in: "port = 1234L;".
.SH "CONFIGURATION KEYS"
.BR jal_subscribe (8)
recognizes the following configuration options:
.TP
.B private_key
The path to a PEM formatted private key that
.BR jal_subscribe (8)
will use for TLS negotiations.  This is ignored if TLS is not enabled.
.TP
.B public_cert
The path to a PEM formatted public certificate file that
.BR jal_subscribe (8)
will use for TLS negotiations.  This is ignored if TLS is not enabled.
.TP
.B remote_cert
The path to a directory that contains PEM formated certificates. These will be used to authenticate remote
.SM JALoP
peers. See the documentation for
.BR c_rehash,
and
.BR x509 (1),
specifically the sections regarding the
.B \-hash
and/or
.B \-subject_hash
options for details on how to create the files in this directory.  This is ignored if TLS is not enabled.
.TP
.B db_root
This identifies where
.BR jal_subscribe (8)
should obtain/store all the records. This is optional and defaults to
.IR /var/lib/jalop/db/ .
.TP
.B host
The IP or hostname of the remote
.SM JALoP
peer to connect to.
.TP
.B port
A numeric value that indicates the port to connect to.
.TP
.B pending_digest_max
A numeric value that indicates the maximum number of records to receive before sending a 'digest' message.
.TP
.B pending_digest_timeout
A numeric value that indicates the maximum number of milliseconds to wait before sending a 'digest' message.
.TP
.B data_class
A list of strings that indicates the type(s) of
.SM JALoP
records to subscribe to.
The strings may be any combination of "\fIjournal\fR", "\fIaudit\fR", or
\fIlog\fR".
.TP
.B session_timeout
Specially formatted string (HH:MM:SS) that specifies the amount of time jal_subscribe will remain connected to the remote publisher.
.TP
.B window_size
Set the window size for beep channels to be this number * 1024. Beep recommends a minimum size of 4096.
.TP
.B digest_algorithms
A bracket enclosed list of any combination of the strings "journal", "audit", and/or "log". Specifies the types of records which the subscriber will accept from the publisher.
.TP
.B journal_resume_threshold_size
Specify the minimum size payload for which a journal resume will be attempted
< 0 disables journal resume
0 means always attempt a resume (default)
> 0 means attempt a resume if the size of already received data is greater than this value
.TP
.B seccomp
This config section contains the configuration settings for seccomp.
.SH "SECCOMP CONFIGURATION"
There are separate configuration settings for syscalls to allow on different OS versions.
.TP
.B enable
seccomp will restrict the process to the defined system calls.
.TP
.B debug
Enable debugging messages for seccomp
.TP
.B version
This sets what config section corresponding to OS version that will be used for the seccomp syscall allow list.
.TP
.B initial
System calls allowed in the setup phase only.
.TP
.B both
System calls allowed in all phases.
.TP
.B final
System calls allowed in the setup phase and while the process is running.
.SH EXAMPLES
.nf
# The path to the private key, used for TLS.
private_key = "./test-input/TLS_CA_Signed/client/jal_subscriber_v1_client.key.pem";

# The path to the public cert, used for TLS.
public_cert = "./test-input/TLS_CA_Signed/client/jal_subscriber_v1_client.cert.pem";

# Directory containing the certificates for the remote peers.
remote_cert = "./test-input/TLS_CA_Signed/client/trust_store_dir";

# The path to the root of the database.
db_root = "./subdb";

# The port to connect on.
port = 1234L;

# The hostname or IP address of the Publisher to subscribe to.
host = "127.0.0.1";

# For subscribe, the maximum number of records to send before sending a 'digest-challenge' message
pending_digest_max = 10L;

# For subscribe, the maximum number of milliseconds to wait, before sending a 'digest-challenge' message
# 1000L = 1 second
pending_digest_timeout = 1000L;

# The supported record types.
data_class = [ "audit", "log", "journal" ];

# Mode to request data in.  May be "archive" or "live".
mode = "archive";

# The time before jal_subscribe ends (HH:MM:SS). Specify 00:00:00 to run continuously.
session_timeout = "00:00:00";

# This window size for the beep channels created
# will be set to this number * 1024 (1k)
# Beep recommends a minimal size of 4k
window_size = 4;

# A list of supported digest algorithms. These algorithms should be ordered by preference
# in a single double-quoted string with a space separating the algorithms.
# Valid values are "sha256", "sha384", and "sha512"
digest_algorithms = "sha256";

# Specify the threshold size at which a journal resume is "worthwhile"
# If a partial journal record is found during session init that exceeds this threshold
# then a journal resume will be performed
# If the partial record is less than this size, the resume will be skipped and the
# record will be transferred from scratch.
# The special value 0 means always resume (default)
# Any negative number disables resume entirely
journal_resume_threshold_size = 1048576L; #1024*1024 = 1MB (1,048,576 bytes)

# seccomp will restrict the jal-local-store process to the defined system calls.
# When the process is in the setup phase, at startup, it will be restricted to the
# initial_seccomp_rules, both_seccomp_rules and final_seccomp_rules system call sets. After the setup phase and before the process
# is doing its routine work, it will be further restricted to only the both_seccomp_rules and final_seccomp_rules system call set.
#
seccomp:
{
    enable = false;
    debug = false;
    version = "rhel_8_9";
    rhel_8_9:
    {
        initial = ["access","arch_prctl","bind","brk","execve","faccessat2","flock","fstat","fstatfs","getcwd","lstat","prctl","recvmsg","readlink","rt_sigprocmask","seccomp","set_tid_address","writev"]
        both = ["clone","clone3","close","fcntl","getpid","ioctl","lseek","mmap","mprotect","munmap","newfstatat","open","openat","prlimit64","read","rseq","rt_sigaction","set_robust_list","stat","write"]
        final = ["clock_nanosleep","connect","epoll_create","epoll_ctl","epoll_wait","exit","exit_group","fdatasync","fsync","ftruncate","futex","getdents","getdents64","getpeername","getppid","getrandom","getrlimit","gettid","getuid","getsockname","madvise","mkdir","nanosleep","poll","pread64","pwrite64","recvfrom","rename","rt_sigreturn","sched_getaffinity","sched_yield","select","sendto","setsockopt","shutdown","socket","sysinfo"]
    };
    rhel_7:
    {
        initial = ["access","arch_prctl","bind","brk","execve","flock","fstatfs","getcwd","lstat","prctl","recvmsg","readlink","rt_sigprocmask","seccomp","set_tid_address"]
        both = ["clone","close","fcntl","fstat","getpid","ioctl","lseek","mmap","mprotect","munmap","newfstatat","open","openat","prlimit64","read","rt_sigaction","set_robust_list","stat","write"]
        final = ["clock_nanosleep","connect","epoll_create","epoll_ctl","epoll_wait","exit","exit_group","fdatasync","fsync","ftruncate","futex","getdents","getdents64","getpeername","getppid","getrandom","getrlimit","gettid","getuid","getsockname","madvise","mkdir","nanosleep","poll","pread64","pwrite64","recvfrom","rename","rt_sigreturn","sched_getaffinity","sched_yield","select","sendto","setsockopt","shutdown","socket","sysinfo"]
    };
};

.SH "SEE ALSO"
.BR jal_subscribe (8),
.BR openssl (1)
