.TH JALDB_TAIL 8
.SH NAME
.B jaldb_tail
\-
.SM JALoP
database tail utility
.SH SYNOPSIS
.B jaldb_tail
[\fIOPTION\fR...]
.SH "DESCRIPTION"
The
.B jaldb_tail
tool is similar to the UNIX
.BR tail (1)
utility.
The
.B jaldb_tail
tool queries the specified JAL database and lists the last 20 records by default.
The
.B jaldb_tail
utility accepts a number of parameters,
including switches to filter the records.
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-follow\fR
Output additional records as the database grows.
.TP
\fB\-n K\fR, \fB\-\-records=K\fR
Output the most recent \fBK\fR records.
.TP
\fB\-t T\fR, \fB\-\-type=T\fR
Select JALoP record type to output.
\fBT\fR may be the letter \fIj\fR (for journal records),
\fIa\fR (for audit records),
or \fIl\fR (for log records).
The default behavior displays log records.
.TP
\fB\-d D\fR, \fB\-\-data=D\fR
Specifies which section of the data should be outputted, options are \fIa\fR for application metadata, \fIs\fR for system metadata, \fIp\fR for the payload (raw journal, audit, or log data), or \fIi\fR for record ID (UUID-Timestamp) only. The default is to output the record ID only. To retrieve all portions of a record, use "z".
.TP
\fB\-h H\fR, \fB\-\-home=H\fR
Specify the root of the JALoP database, defaults to
.I /var/lib/jalop/db/
.TP
\fB\-v\fR, \fB\-\-version\fR
Output the version information and exit.
.SH "SEE ALSO"
.BR jald (8),
.BR jal-local-store (8),
.BR jal-local-store.config (5),
.BR jal_dump (8),
.BR jal_purge (8)
.BR jal_subscribe (8),

