.TH JALDB_INLINE_FILTER.CONFIG 5
.SH NAME
.BR jaldb_inline_filter.config
- configuration file for
.BR jaldb_inline_filter (8)
.SH "DESCRIPTION"
This file is read by
.BR jaldb_inline_filter (8)
and specifies the configuration parameters
such as database path and socket path.
This file follows the TOML format, where each
configuration setting is in the form "key = value;".
Blank lines and lines starting with "#" are ignored.
String values must be enclosed in double quotes.  The
format's specification can be found at https://toml.io/en/v1.0.0.
.SH "CONFIGURATION KEYS"
.BR jaldb_inline_filter (8)
recognizes the following configuration options:
.SH "db"
This config section contains settings that apply to the JALoP database.
.TP
.B path
The path to the JALoP database
.SH "control-socket"
This config section contains settings that apply to the control Unix Domain Socket (UDS).
.TP
.B path
The path to the control socket
.TP
.B buffer
The buffer size in bytes to use for this socket.
.SH "record-socket"
This config section contains settings that apply to the record Unix Domain Socket (UDS).
.TP
.B path
The path to the record socket
.TP
.B timeout
The timeout in seconds for waiting for an incoming connection on this socket.
.TP
.B buffer
The buffer size in bytes to use for this socket.
.SH "seccomp"
This config section contains the configuration settings for seccomp.
.TP
.B enabled
seccomp will restrict the process to the defined system calls.
.TP
.B debug
Enable debugging messages for seccomp
.TP
.B initial
System calls allowed in the setup phase only.
.TP
.B both
System calls allowed in all phases.
.TP
.B final
System calls allowed in the setup phase and while the process is running.
.TP
.B rhel7_initial
RHEL7 System calls allowed in the setup phase only.
.TP
.B rhel7_both
RHEL7 System calls allowed in all phases.
.TP
.B rhel7_final
RHEL7 System calls allowed in the setup phase and while the process is running.

.SH EXAMPLES
.nf
[db]
path = "testdb"

[control-socket]
path = "jald_filter_socket_request"
buffer = 4096

[record-socket]
path = "jald_filter_socket"
timeout = 30
buffer = 256

[seccomp]
enabled = false
debug = false

initial = ["access", "arch_prctl", "bind", "epoll_create1", "eventfd2", "execve", "getrandom", "ioctl", "listen", "poll", "prlimit64", "seccomp", "set_tid_address", "socketpair"]
final = ["accept4", "connect", "exit", "getpid", "madvise", "pwrite64", "recvfrom", "rt_sigreturn", "sendmsg", "writev"]
both = ["brk", "clone3", "close", "epoll_ctl", "epoll_wait", "exit_group", "fcntl", "fstat", "fstatfs", "futex", "lseek", "mmap", "mprotect", "munmap", "newfstatat", "openat", "prctl", "pread64", "read", "rseq", "rt_sigaction", "rt_sigprocmask", "sched_getaffinity", "sched_yield", "set_robust_list", "sigaltstack", "socket", "statx", "stat", "write"]

# el7 requires an alternative set of syscalls
rhel7_initial = ["access", "arch_prctl", "bind", "epoll_create1", "eventfd2", "execve", "getrandom", "listen", "poll", "prlimit64", "seccomp", "set_tid_address", "socketpair"]
rhel7_final = ["accept4", "exit", "getpid", "madvise", "pwrite64", "recvfrom", "rt_sigreturn", "sendmsg", "writev"]
rhel7_both = ["brk", "clone", "close", "connect", "epoll_ctl", "epoll_wait", "exit_group", "fcntl", "fstat", "fstatfs", "futex", "ioctl", "lseek", "mmap", "mprotect", "munmap", "newfstatat", "open", "openat", "prctl", "pread64", "read", "rt_sigaction", "rt_sigprocmask", "rt_sigreturn", "sched_getaffinity", "sched_yield", "set_robust_list", "sigaltstack", "socket", "statx", "stat", "uname", "write"]

.SH "SEE ALSO"
.BR jald_inline_filter (8)
