.TH JALP_TEST 8
.SH NAME
.BR jalp_test
- JALoP database test utility
.SH SYNOPSIS
.B jalp_test
[\fIOPTION\fR...]
.SH "DESCRIPTION"
.B jalp_test
is a tool used to send log, audit, or journal records to a JALoP database.
.SH OPTIONS
.TP
\fB\-a\fR
(optional) the full, or relative path to a file to use for generating the application metadata.
.TP
\fB\-p\fR
The full or relative path to a file that should be used as the payload for this particular record.
.TP
\fB\-s\fR
Indicates the payload should be taken from <stdin>.
.TP
\fB\-t\fR, \fB\-\-type=T\fR
Indicates which type of data to send:
.I j
(for journal records),
.I a
(for audit records),
.I l
(for log records), or
.I f
(for journal record using file descriptor passing).
.TP
\fB\-h\fR
Print a summary of options.
.TP
\fB\-j\fR
The full or relative path to the JALoP socket.
.TP
\fB\-k\fR
The full or relative path to a key file to be used for signing. Must also specify '-a'.
.TP
\fB\-c\fR
The full or relative path to a certificate file to be used for signing. Requires '-k'.
.TP
\fB\-d\fR
Calculates and adds a SHA256 digest of the payload to the application metadata. Must also specify '-a'.
.TP
\fB\-x\fR
The full or relative path to the JALoP Schemas.
.TP
\fB\-v\fR, \fB\-\-version\fR
Outputs the version number and exits.

.SH "SEE ALSO"
.BR jald (8),
.BR jal-local-store(8),
.BR jalp_test (8),
.BR jal_subscribe (8)
