Import('*')
mandir = env['DESTDIR'] + env.subst(env['MANDIR'])

progs_pages = env.Glob('*.8')
cfgs_pages = env.Glob('*.5')
env.Alias('install', env.Install(mandir + '/man/man8/', progs_pages))
env.Alias('install', env.Install(mandir + '/man/man5/', cfgs_pages))

