Import('*')

env = env.Clone()

env.MergeFlags(env['vortex_cflags'])
env.MergeFlags(env['vortex_ldflags'])
env.MergeFlags({'CPPPATH':'#src/network_lib/src:#src/lib_common/include:#src/network_lib/include:#src/lib_common/src:#src/db_layer/src/:.'.split(':')})

dummy_net_server = env.Program(target='dummy_net_server', source=["dummy_net_server.c", lib_common, network_lib])

env.Default(dummy_net_server)
