Import('*')

jal_utils = env.SharedLibrary(target='jal-utils', source=env.Glob("*.c"))
env.Default(jal_utils)
if (env['release']):
	libdir = env['DESTDIR'] + env.subst(env['LIBDIR'])
	env.Alias('install', env.Install(libdir, jal_utils))

Return("jal_utils")
