Import('*')
from Utils import install_for_build

sources = env.Glob("*.c") + env.Glob("*.cpp")

db_lib = env.SharedLibrary(target='jal-db', source=[sources])
env.Default(db_lib)

install_for_build(env, 'lib', db_lib)
if (env['release']):
	libdir = env['DESTDIR'] + env.subst(env['LIBDIR'])
	env.Alias('install', env.Install(libdir, db_lib))

Return("db_lib")
