Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = utilsEnv.Clone()

sources = env.Glob("*.cpp")

env.MergeFlags({'CPPPATH':'#src/db_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})
env.MergeFlags("-Wno-shadow")

add_project_lib(env, 'db_layer', 'jal-db')
add_project_lib(env, 'lib_common', 'jal-common')

jal_purge = env.Program(target='jal_purge', source=[sources, lib_common, db_layer])
env.Default(jal_purge)
install_for_build(env, 'bin', jal_purge)

Return("jal_purge")
