Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = utilsEnv.Clone()

sources = env.Glob("*.cpp")

env.MergeFlags({'CPPPATH':'#src/db_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})
env.MergeFlags(env['dbxml_ldflags'])
env.MergeFlags(env['dbxml_cflags'])
env.MergeFlags("-Wno-shadow")

jal_purge_objs = env.SharedObject(source=sources)

jal_purge = env.Program(target='jal_purge', source=jal_purge_objs)
env.Default(jal_purge)
if env['variant'] == 'release':
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, jal_purge))

install_for_build(env, 'bin', jal_purge)

Return("jal_purge")
