Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = env.Clone()

env.MergeFlags(env['lmdb_cflags'])
env.MergeFlags(env['lmdb_ldflags'])

env.MergeFlags("-lboost_filesystem -lboost_system")

sources = env.Glob("*.cpp")

env.MergeFlags({'CPPPATH':'#src/lmdb_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})
add_project_lib(env, 'lmdb_layer', 'jal-db')

jal_purge_objs = env.SharedObject(source=sources)

jal_purge = env.Program(target='jal_purge', source=jal_purge_objs)
env.Default(jal_purge)
if env['variant'] == 'release':
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, jal_purge))

install_for_build(env, 'bin', jal_purge)

Return("jal_purge")
