[package]
name = "jalop-filter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jaldb_inline_filter"
path = "src/main.rs"

[dependencies]
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11"
nix = { version = "0.29", features = ["uio", "socket"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
toml = { version = "1.0", default-features = false, features = ["serde", "parse"] }

jalop-sys = { path = "../jalop-sys" }
jalop-sec = { path = "../jalop-sec" }
jalop-actors = { path = "../jalop-actors" }
jalop-util = { path = "../jalop-util" }
jalop-protocol = { path = "../jalop-protocol" }

[dev-dependencies]
assert_matches = "1.5"

[features]
default = []
rhel10 = ["jalop-sys/rhel10", "jalop-sec/rhel10"]
rhel9 = ["jalop-sys/rhel9", "jalop-sec/rhel9"]
rhel8 = ["jalop-sys/rhel8", "jalop-sec/rhel8"]
