import os
import string
Import('*')

producer_root = os.path.join('..', '..', 'producer_lib', 'src')
suffix = env['SHOBJSUFFIX']

tests = []
# Will need to uncomment out the following to build...
# tests.append(env.TestDeptTest('test_jalp_foo.c', other_sources=[os.path.join(producer_root, 'jalp_bar' + suffix)], shared_object=True)[0].abspath)

producer_tests = env.Alias('producer_tests', tests, 'test_dept ' + " ".join(tests))
AlwaysBuild(producer_tests)
env.Depends(all_tests, producer_tests)


