import os
from Utils import recursive_glob

Import('*')

utilsEnv = env.Clone()

utilsEnv.MergeFlags(utilsEnv['lfs_cflags'])
utilsEnv.MergeFlags(utilsEnv['libconfig_cflags'])
utilsEnv.MergeFlags(utilsEnv['libconfig_ldflags'])

subdirs = """
	    jalp_test
	    testserver
	  """.split()

jalp_test = utilsEnv.SConscript('jalp_test/SConscript', exports='utilsEnv all_tests lib_common producer_lib')
jalp_dump = utilsEnv.SConscript('jal_dump/SConscript', exports='utilsEnv all_tests lib_common db_layer')
jal_purge = utilsEnv.SConscript('jal_purge/SConscript', exports='utilsEnv all_tests lib_common db_layer')
testserver = utilsEnv.SConscript('testserver/SConscript', exports='utilsEnv all_tests lib_common')
testpush = utilsEnv.SConscript('testpush/SConscript', exports='utilsEnv lib_common network_lib')
dummy_net_server = utilsEnv.SConscript('dummy_net_server/SConscript', exports='utilsEnv lib_common network_lib')
testsub = utilsEnv.SConscript('testsub/SConscript', exports='utilsEnv lib_common network_lib')
sid_dump = utilsEnv.SConscript('sid_dump/SConscript', exports='utilsEnv all_tests lib_common db_layer')
jaldb_tail = utilsEnv.SConscript('jaldb_tail/SConscript', exports='utilsEnv all_tests lib_common db_layer')

Return("jalp_test")
