import os
from Utils import recursive_glob

Import('*')

utilsEnv = env.Clone()

utilsEnv.MergeFlags(utilsEnv['libconfig_cflags'])
utilsEnv.MergeFlags(utilsEnv['libconfig_ldflags'])


subdirs = """
	    jalp_test
	    testserver
	  """.split()

jalp_test = utilsEnv.SConscript('jalp_test/SConscript', exports='utilsEnv all_tests lib_common producer_lib')
jalp_dump = utilsEnv.SConscript('jal_dump/SConscript', exports='utilsEnv all_tests lib_common db_layer')
testserver = utilsEnv.SConscript('testserver/SConscript', exports='utilsEnv all_tests lib_common')
testpush = utilsEnv.SConscript('testpush/SConscript', exports='utilsEnv lib_common network_lib')
dummy_net_server = utilsEnv.SConscript('dummy_net_server/SConscript', exports='utilsEnv lib_common network_lib')

Return("jalp_test")
