import os
from Utils import recursive_glob

Import('*')

utilsEnv = env.Clone()

utilsEnv.MergeFlags(utilsEnv['libconfig_cflags'])
utilsEnv.MergeFlags(utilsEnv['libconfig_ldflags'])


subdirs = """
	    jalp_test
	    testserver
	  """.split()

jalp_test = utilsEnv.SConscript('jalp_test/SConscript', exports='utilsEnv all_tests lib_common producer_lib')
testserver = utilsEnv.SConscript('testserver/SConscript', exports='utilsEnv all_tests lib_common')

Return("jalp_test")
