[package]
name = "jalop-sec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
libseccomp = "0.4"
log = "0.4"

jalop-sys = { path = "../jalop-sys" }

[features]
default = []
rhel10 = ["jalop-sys/rhel10"]
rhel9 = ["jalop-sys/rhel9"]
rhel8 = ["jalop-sys/rhel8"]
