---

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: stop jal-local-store
    shell: 
      cmd: 'killall {{cwd}}/release/bin/jal-local-store || true'
  - name: clear database
    file:
        path: '{{cwd}}/testdb'
        state: absent
  - name: remove socket
    file: 
        path: '{{cwd}}/jal.sock' 
        state: absent
  - name: make database directory
    file:
        path: '{{cwd}}/testdb'
        state: directory
  - name: copy DB_CONFIG
    shell: 
        cmd: 'cp {{cwd}}/test-input/DB_CONFIG {{cwd}}/testdb || true'
  - name: start jal-local-store
    command: 
        chdir: '{{cwd}}'
        cmd:  './release/bin/jal-local-store -c ./test-input/local_store.cfg -d '
  - name: send logs
    async: 45
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './release/bin/jalp_test -j ./jal.sock -p ./test-input/big_payload.txt -n 4000 -t l'
  - name: send journals
    async: 45
    poll: 0
    command:
        chdir: '{{cwd}}'
        cmd: './release/bin/jalp_test -j ./jal.sock -p ./test-input/big_payload.txt -n 1000 -t j'
  - name: send audits
    command:
        chdir: '{{cwd}}'
        cmd: './release/bin/jalp_test -j ./jal.sock -a ./test-input/sample2.cfg -p ./test-input/good_audit_input.xml -n 500 -t a'
#call with this command from jalop home
##ansible-playbook src/test_utils/scripts/local-store-tests.yml -e cwd=`pwd`

