Import('*')

env = utilsEnv.Clone()
env.MergeFlags(env['vortex_cflags'])
env.MergeFlags(env['vortex_ldflags'])
env.MergeFlags({'CPPPATH':'#src/network_lib/src:#src/lib_common/include:#src/network_lib/include:#src/lib_common/src:#src/db_layer/src/:.'.split(':')})

testpush = env.Program(target='dummy_push', source=["push.c", lib_common, network_lib])

env.Default(testpush)
