Import('*')

env = env.Clone()
env.MergeFlags({'CPPPATH':'#src/network_lib/src:#src/lib_common/include:#src/network_lib/include:#src/lib_common/src:#src/db_layer/src/:.'.split(':')})
env.MergeFlags('-pthread')

testpush = env.Program(target='dummy_push', source=["push.c", lib_common, network_lib])

env.Default(testpush)
