import os
import string
Import('*')

env = env.Clone()

tests = []

# The test code triggers warnings we'd just as soon ignore
# -fcommon needed to restore original gcc behavior in rhel9 to prevent multiple definition linker errors
ccflags = ' -fcommon -Wno-format-nonliteral -DSCHEMAS_ROOT=\\"' + net_stores_env['SOURCE_ROOT'] + '/schemas/\\" -DTEST_INPUT_ROOT=\\"' + net_stores_env['SOURCE_ROOT'] + '/test-input/\\" '

env.Append(RPATH=os.path.dirname(str(lib_common[0])))
env.Append(CCFLAGS=ccflags.split())
env.MergeFlags({'CPPPATH':'#src/network_stores/src:#src/lib_common/src:#src/test_utils/src'.split(':')})

db_layer_obj = net_stores_env.SharedObject("../src/jsub_db_layer.cpp")

tests.append(env.TestDeptTest('test_jsub_db_layer.cpp',
	other_sources=[lib_common, db_layer, jal_utils, network_lib])[0].abspath)

net_store_tests = env.Alias('net_store_tests', tests, 'test_dept ' + " ".join(tests))

AlwaysBuild(net_store_tests)

env.Depends(all_tests, net_store_tests)
