Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = utilsEnv.Clone()

sources = env.Glob("*.cpp")

env.MergeFlags({'CPPPATH':'#src/db_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})

add_project_lib(env, 'db_layer', 'jal-db')
add_project_lib(env, 'lib_common', 'jal-common')

sid_dump = env.Program(target='jal_sid_dump', source=[sources, lib_common, db_layer])
env.Default(sid_dump)
if env['variant'] == 'release':
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, sid_dump))

install_for_build(env, 'bin', sid_dump)

Return("sid_dump")
