[package]
name = "jalop-jald"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jald_rs"
path = "src/main.rs"

[dependencies]
thiserror = "2"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
toml = { version = "1.0", default-features = false, features = ["serde", "parse"] }
nix = { version = "0.29", features = ["uio", "socket", "fs", "poll"] }
async-trait = "0.1"
tokio-util = { version = "0.7", features = ["codec"] }
futures-util = { version = "0.3", default-features = false, features = ["std", "sink"] }
reqwest = { version = "0.13", default-features = false, features = ["native-tls", "stream"] }
url = { version = "2.5.2", features = ["serde"] }

jalop-sys = { path = "../jalop-sys" }
jalop-sec = { path = "../jalop-sec" }
jalop-actors = { path = "../jalop-actors" }
jalop-util = { path = "../jalop-util" }
jalop-protocol = { path = "../jalop-protocol" }

[features]
default = []
rhel10 = ["jalop-sys/rhel10", "jalop-sec/rhel10"]
rhel9 = ["jalop-sys/rhel9", "jalop-sec/rhel9"]
rhel8 = ["jalop-sys/rhel8", "jalop-sec/rhel8"]
