Import('*')

lib_common_env = env.Clone()
lib_common_env.Prepend(CPPPATH='#src/lib_common/include:#src/lib_common/src')

lib_common_env.Append(CCFLAGS=lib_common_env['openssl_cflags'])
lib_common_env.Append(CCFLAGS=lib_common_env['xerces_cflags'])
lib_common_env.Append(CCFLAGS=lib_common_env['santuario_ldflags'])

lib_common_env.Append(LINKFLAGS=lib_common_env['openssl_ldflags'])
lib_common_env.Append(LINKFLAGS=lib_common_env['xerces_ldflags'])
lib_common_env.Append(LINKFLAGS=lib_common_env['libuuid_ldflags'])
lib_common_env.Append(LINKFLAGS=lib_common_env['santuario_ldflags'])


lib_common = SConscript('src/SConscript', exports={'env':lib_common_env})
SConscript('test/SConscript', exports={'env':lib_common_env, 'all_tests':all_tests, 'test_utils':test_utils})
Return("lib_common")
