Import('*')
from Utils import add_project_lib
from Utils import install_for_build

env = env.Clone()

sources = []
env.MergeFlags('-D_BSD_SOURCE')

for source in (env.Glob("*.c") + env.Glob("*.cpp")):
	sources.append(source)

add_project_lib(env, 'lib_common', 'jal-common')
add_project_lib(env, 'db_layer', 'jal-db')
add_project_lib(env, 'jal_utils', 'jal-utils')

local_store = env.Program(target='jal-local-store', source=sources)
env.Depends(local_store, [lib_common, db_layer, jal_utils])

env.Default(local_store)
if (env['release']):
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, local_store))


install_for_build(env, 'bin', local_store)

Return("local_store env")
