Import('*')

local_store_objs = env.SharedObject(source=[env.Glob("*.c")])
local_store = env.Program(target='jal-local-store', source=[local_store_objs, jal_utils])
env.Default(local_store)
if (env['release']):
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, local_store))

Return("local_store")
