Import('*')
import os

if env['release']:
	schemas_dir = env['DESTDIR'] + env['JALOP_SCHEMAS_ROOT']
	env.Alias('install', env.Install(schemas_dir, env.Glob("*.xsd")))
	env.Alias('install', env.Install(schemas_dir, env.Glob("*.dtd")))

