Import('*')
import os
from Utils import install_for_build

sources = []
for source in (env.Glob("*.c")):
	if not source.name == 'jal_asprintf.c':
		sources.append(source)
sources = sources + env.Glob("*.cpp")
# GCC on solaris and RHEL 5 don't support #pragma GCC diagnostic to disable warnings, so disable it here.
asprintf_obj = env.SharedObject(source='jal_asprintf.c', CCFLAGS=env['CCFLAGS'] + '-Wno-missing-format-attribute -Wno-unreachable-code'.split())

lib_common = env.SharedLibrary(target='jal-common', source=[sources, asprintf_obj])
env.Default(lib_common)
install_for_build(env, 'lib', lib_common)
if (env['variant'] == 'release'):
	libdir = env['DESTDIR'] + env.subst(env['LIBDIR'])
	env.Alias('install', env.Install(libdir, lib_common))

Return("lib_common")
