#!/bin/bash
$1 --redefine-syms=$2 $3 $4 
#> /dev/null 2>&1
if [ $? -ne 0 ]; then
    while read old_symbol new_symbol
      do
      redefined_syms="$redefined_syms --redefine-sym $old_symbol=$new_symbol"
    done < $2
    $1 $redefined_syms $3 $4
fi

