import os
from Utils import recursive_glob
from Utils import install_for_build
Import('*')

subdirs = """
	    local_store
	    network_stores
	    utils
	  """.split()

AlwaysBuild(all_tests)

variant = env['variant']
matches = recursive_glob('.', '*.gcda')
env.Clean(all_tests, matches)
if env.GetOption('clean'):
	env.Default(all_tests)

test_utils = env.SConscript('test_utils/SConscript', exports='env')
lib_common = env.SConscript('lib_common/SConscript', exports='env all_tests test_utils')

db_layer = env.SConscript('lmdb_layer/SConscript', exports='env all_tests lib_common test_utils')

producer_lib = env.SConscript('producer_lib/SConscript', exports='env all_tests test_utils lib_common')
network_lib = env.SConscript('network_lib/SConscript', exports='env all_tests lib_common test_utils')
jal_utils = env.SConscript('jal_utils/SConscript', exports='env')
for d in subdirs:
		env.SConscript('%s/SConscript' % d, exports='env all_tests test_utils lib_common producer_lib db_layer jal_utils network_lib')

install_for_build(env, 'src', Dir('.').srcnode().abspath + "/jalop-rust")
jaldb_inline_filter = env.SConscript('jalop-rust/SConscript', exports='env db_layer')
install_for_build(env, 'bin', f"jalop-rust/target/{variant}/jaldb_inline_filter")
