import os
from Utils import recursive_glob

Import('*')

subdirs = """
	    local_store
	    network_lib
	    network_stores
	    producer_lib
	  """.split()

AlwaysBuild(all_tests)

matches = recursive_glob('.', '*.gcda')
env.Clean(all_tests, matches)
if env.GetOption('clean'):
	env.Default(all_tests)

test_utils = env.SConscript('test_utils/SConscript', exports='env')
lib_common = env.SConscript('lib_common/SConscript', exports='env all_tests test_utils')
for d in subdirs:
	env.SConscript('%s/SConscript' % d, exports='env all_tests lib_common test_utils')
