Import('*')
from Utils import install_for_build
from Utils import add_project_lib

env = env.Clone()

env.MergeFlags(env['lmdb_cflags'])
env.MergeFlags(env['lmdb_ldflags'])

sources = env.Glob("*.cpp")
add_project_lib(env,'json_c','json-c')

env.MergeFlags({'CPPPATH':'#src/lmdb_layer/src:#src/lib_common/include:#src/lib_common/src/:.'.split(':')})
add_project_lib(env, 'lmdb_layer', 'jal-db')

jaldb_tool_objs = env.SharedObject(source=sources)

jaldb_tool = env.Program(target='jaldb_tool', source=jaldb_tool_objs)
env.Default(jaldb_tool)
if env['variant'] == 'release':
	sbindir = env['DESTDIR'] + env.subst(env['SBINDIR'])
	env.Alias('install', env.Install(sbindir, jaldb_tool))

install_for_build(env, 'bin', jaldb_tool)

Return("jaldb_tool")
