Import('*')

producer_lib = env.Clone()
producer_lib.Prepend(CPPPATH='#src/producer_lib/include:#src/lib_common/include:#src/producer_lib/src')
producer_lib.Append(CFLAGS=producer_lib['openssl_cflags'])
producer_lib.Append(LDFLAGS=producer_lib['openssl_ldflags'])

SConscript('src/SConscript', exports={'env':producer_lib})
SConscript('test/SConscript', exports={'env':producer_lib, 'all_tests':all_tests})
