Import('*')

producer_lib = env.Clone()
producer_lib.Prepend(CPPPATH='#src/producer_lib/include:#src/lib_common/include:#src/producer_lib/src')

SConscript('src/SConscript', exports={'env':producer_lib})
SConscript('test/SConscript', exports={'env':producer_lib, 'all_tests':all_tests})
