import os
Import('*')
env = env.Clone()

env.MergeFlags({'CPPPATH': '#src/network_lib/src:#src/network_lib/include:#src/lib_common/include:#src/lib_common/src:.'.split(':')})
env.MergeFlags(env['vortex_cflags'])
env.MergeFlags(env['vortex_ldflags'])
env.MergeFlags(env['vortex_tls_cflags'])
env.MergeFlags(env['vortex_tls_ldflags'])
# The vortex libraries shadow global variables, so disable the warning here.
env.MergeFlags({'CCFLAGS': '-Wno-shadow'.split()})

SConscript('include/SConscript', exports='env all_tests lib_common')
SConscript('test/SConscript', exports='env all_tests lib_common test_utils')

network_lib = SConscript('src/SConscript', exports='env')
Return('network_lib')
