import os
Import('*')
env = env.Clone()

env.MergeFlags({'CPPPATH': ('#src/network_lib/src:#src/network_lib/include:' + 
	'#src/lib_common/include:#src/lib_common/src:.').split(':')})

env.MergeFlags(env['lfs_cflags'])
env.MergeFlags(env['axl_cflags'])
env.MergeFlags(env['axl_ldflags'])
env.MergeFlags('-pthread')
env.MergeFlags(env['libcurl_cflags'])
env.MergeFlags(env['libcurl_ldflags'])

network_lib, net_lib_env = SConscript('src/SConscript', exports='env')
SConscript('include/SConscript', exports='env all_tests lib_common')
SConscript('test/SConscript', exports='env net_lib_env all_tests lib_common test_utils')

Return('network_lib')
